server:
  port: 8189
  servlet:
    context-path: /calculator
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/calculator_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
    password: MICROLABtechnosp80
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
logging:
  level:
    ru.khorolskii.shop.shop: DEBUG


